export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCSESS = "ORDER_CREATE_SUCCSESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_REST = "ORDER_CREATE_REST";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCSESS = "ORDER_DETAILS_SUCCSESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCSESS = "ORDER_LIST_SUCCSESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_LIST_DELETE_REQUEST = "ORDER_LIST_DELETE_REQUEST";
export const ORDER_LIST_DELETE_SUCCSESS = "ORDER_LIST_DELETE_SUCCSESS";
export const ORDER_LIST_DELETE_FAIL = "ORDER_LIST_DELETE_FAIL";

export const ORDER_MY_LIST_REQUEST = "ORDER_MY_LIST_REQUEST";
export const ORDER_MY_LIST_SUCCSESS = "ORDER_MY_LIST_SUCCSESS";
export const ORDER_MY_LIST_FAIL = "ORDER_MY_LIST_FAIL";
export const ORDER_MY_LIST_REST = "ORDER_MY_LIST_REST";
export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCSESS = "ORDER_PAY_SUCCSESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_REST = "ORDER_PAY_REST";
export const CART_REST = "CART_REST";

export const ORDER_DELIVERIED_UPDATE_REQUEST = "ORDER_DELIVERIED_UPDATE_REQUEST";
export const ORDER_DELIVERIED_UPDATE_SUCCESS = "ORDER_DELIVERIED_UPDATE_SUCCESS";
export const ORDER_DELIVERIED_UPDATE_FAIL = "ORDER_DELIVERIED_UPDATE_FAIL";
export const ORDER_DELIVERIED_UPDATE_RESET = "ORDER_DELIVERIED_UPDATE_RESET";